recover from (concurrent) handler removal
adhearsion/has-guarded-handlers pull request #6
Opened 2016-10-25 11:40 UTC by kares

... a follow up from https://github.com/adhearsion/has-guarded-handlers/pull/5

(under JRuby) for some specific use-cases more concurrency fixes are needed to run AHN safely.

there's 2 errors @cloudvox managed to run into (using JRuby 1.7) which both related to the same issue 

1. reported (by others) and explained at https://github.com/adhearsion/punchblock/issues/234#issuecomment-212342156
2. triggering a (tmp) handler while another `trigger_handler :ami` is happening concurrently, on JRuby :
```
ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/has-guarded-handlers-4d4980673764/lib/has_guarded_handlers.rb:180:in `handlers_of_type'
	org/jruby/RubyArray.java:1617:in `each'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/has-guarded-handlers-4d4980673764/lib/has_guarded_handlers.rb:178:in `handlers_of_type'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/has-guarded-handlers-4d4980673764/lib/has_guarded_handlers.rb:131:in `trigger_handler'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/punchblock-42cbe4572035/lib/punchblock/translator/asterisk/call.rb:183:in `process_ami_event'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/punchblock-42cbe4572035/lib/punchblock/translator/asterisk.rb:230:in `ami_dispatch_to_or_create_call'
	org/jruby/RubyHash.java:1357:in `each_pair'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/punchblock-42cbe4572035/lib/punchblock/translator/asterisk.rb:228:in `ami_dispatch_to_or_create_call'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/punchblock-42cbe4572035/lib/punchblock/translator/asterisk.rb:112:in `handle_ami_event'
	org/jruby/RubyKernel.java:1932:in `public_send'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/calls.rb:25:in `dispatch'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/calls.rb:122:in `dispatch'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/actor.rb:322:in `handle_message'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/actor.rb:416:in `task'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/tasks.rb:55:in `initialize'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/tasks.rb:47:in `initialize'
	/srv/phone/apptastic/shared/bundle/jruby/1.9/bundler/gems/celluloid-7af615463b10/lib/celluloid/tasks/task_fiber.rb:13:in `create'
```

they both happen since [`PB::Translator::Asterisk::Call` instances are no longer actors](https://github.com/adhearsion/punchblock/commit/f939ecabed9f4922cf446cc22ff1d0e42c9632e5#diff-2d5dcf5f36f13b8f6dec5cebaf989d43L10) ... the changes proposed assure this case is covered correctly.

alternatives to solving the issue would be : 
1. introduce mutex locking (possibly only around `Call`'s handler triggering)
2. rewrite HGH to be fully thread-safe (there's still no guarantee a tmp handler won't fire twice)
3. avoid [tmp handler registration](https://github.com/cloudvox/punchblock/blob/dialogtech/support/2.7.5.dt2/lib/punchblock/translator/asterisk/call.rb#L295) in `Call` instances (there's also [one in `Component::Record`](https://github.com/cloudvox/punchblock/blob/dialogtech/support/2.7.5.dt2/lib/punchblock/translator/asterisk/component/record.rb#L25))

2016-11-17 15:41 UTC, sfgeorge commented
@benlangfeld could you share your thoughts when you get a chance?

2016-11-18 11:05 UTC, benlangfeld requested changes
Changelog entry please :)

2016-11-18 11:49 UTC, benlangfeld approved these changes

2016-11-18 11:49 UTC, benlangfeld commented
This just needs conflicts resolving :)

2016-11-18 11:51 UTC, kares commented
meh the changelog ... on it!

2016-11-18 11:53 UTC, kares commented
rebased, thanks for looking into it Ben.

2016-11-18 12:07 UTC, merged